version: "3.4"
services:
  access-service:
    build:
      context: ./access-service/
      dockerfile: Dockerfile
      network: host
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - access-service-db
    ports:
      - "3033:3000"
    volumes:
      - ./access-service:/app
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped

  access-service-db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "15432:5432"
    volumes:
      - /tmp/access-service-db:/var/lib/postgresql/data
    restart: always
