version: "3.4"

services:
  access-service:
    build:
      context: ./access-service/
      dockerfile: Dockerfile
    command: yarn dev
    depends_on:
      - discovery
      - access-service-db
    env_file: ./access-service/.env
    ports:
      - "3032:3333"
    volumes:
      - ./access-service:/app
    networks:
      - app-network
    restart: unless-stopped

  access-service-db:
    image: mongo
    volumes:
      - /tmp/access-service-db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - app-network
    restart: always

  account-service:
    build:
      context: ./account-service/
      dockerfile: Dockerfile
    command: yarn dev
    depends_on:
      - discovery
      - account-service-db
    env_file: ./account-service/.env
    ports:
      - "3033:3333"
    volumes:
      - ./account-service:/app
    networks:
      - app-network
    restart: unless-stopped

  account-service-db:
    image: mongo
    volumes:
      - /tmp/account-service-db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - app-network
    restart: always

  bet-service:
    build:
      context: ./bet-service/
      dockerfile: Dockerfile
    command: yarn dev
    depends_on:
      - discovery
      - bet-service-db
    env_file: ./bet-service/.env
    ports:
      - "3034:3333"
    volumes:
      - ./bet-service:/app
    networks:
      - app-network
    restart: unless-stopped

  bet-service-db:
    image: mongo
    volumes:
      - /tmp/bet-service-db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - app-network
    restart: always

  match-service:
    build:
      context: ./match-service/
      dockerfile: Dockerfile
    command: yarn dev
    depends_on:
      - discovery
    env_file: ./match-service/.env
    ports:
      - "3035:3333"
    volumes:
      - ./match-service:/app
    networks:
      - app-network
    restart: unless-stopped

  api-gateway:
    build:
      context: ./api-gateway/
      dockerfile: Dockerfile
    command: yarn dev
    depends_on:
      - discovery
    ports:
      - "3030:3333"
    volumes:
      - ./api-gateway:/app
    networks:
      - app-network
    restart: unless-stopped

  discovery:
    image: consul:latest
    command: "agent"
    ports:
      - "3031:8500"
      - "8600:53/tcp"
      - "8600:53/udp"
    volumes:
      - ./discovery/server.json:/consul/config/server.json:ro
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
