version: "3.4"

services:
  access-service:
    build:
      context: ./access-service/
      dockerfile: Dockerfile
    command: yarn dev
    depends_on:
      - discovery
      - access-service-db
    environment:
      - APP_URL=http://access-service:3333
      - CLIENT_URL=http://frontend:3000
      - MONGO_URL=mongodb://root:root@access-service-db:27017/?retryWrites=true&w=majority
      - APP_SECRET=wteAAz2PcNO6GspgBILwE2YHwQr2l8VxXBFfIHVR0Xh4J43fHVhHDFGIld0ZBKA
    ports:
      - "3033:3333"
    volumes:
      - ./access-service:/app
    networks:
      - app-network
    restart: unless-stopped

  access-service-db:
    image: mongo
    volumes:
      - /tmp/access-service-db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - app-network
    restart: always

  discovery:
    image: consul:latest
    command: "agent"
    ports:
      - "8500:8500"
      - "8600:53/tcp"
      - "8600:53/udp"
    volumes:
      - ./discovery/server.json:/consul/config/server.json:ro
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
