version: "3.4"

services:
  access-service:
    build:
      context: ./access-service/
      dockerfile: Dockerfile
    command: yarn dev
    depends_on:
      - discovery
      - access-service-db
    env_file: ./access-service/.env
    ports:
      - "3033:3333"
    volumes:
      - ./access-service:/app
    networks:
      - app-network
    restart: unless-stopped

  access-service-db:
    image: mongo
    volumes:
      - /tmp/access-service-db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - app-network
    restart: always

  transaction-service:
    build:
      context: ./transaction-service/
      dockerfile: Dockerfile
    command: yarn dev
    depends_on:
      - discovery
      - transaction-service-db
    env_file: ./transaction-service/.env
    ports:
      - "3034:3333"
    volumes:
      - ./transaction-service:/app
    networks:
      - app-network
    restart: unless-stopped

  transaction-service-db:
    image: mongo
    volumes:
      - /tmp/transaction-service-db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - app-network
    restart: always

  discovery:
    image: consul:latest
    command: "agent"
    ports:
      - "8500:8500"
      - "8600:53/tcp"
      - "8600:53/udp"
    volumes:
      - ./discovery/server.json:/consul/config/server.json:ro
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
